config/routes.rb
Rails.application.routes.draw do

  resources :planes

  resources :passenger_tickets

  resources :passengers
  
  root to: 'flights#index', via: [:get, :post]

  match ':controller(/:action(/:id))(.:format)', via: [:get, :post]

end

app/models/plane.rb
class Plane < ActiveRecord::Base
  after_validation  :correCt
  belongs_to        :company
  has_many          :flights

  validates :num, :model, :type, presence: true
  validates :amount_of_seats, :floors, :rows, :buis_st, :eco_st, :prem_st, presence: true, if: "type == 'Пассажирский'"
  validates :type, inclusion: {in: ["Пассажирский","Грузовой"]}
  validates :buis_st, :eco_st, :prem_st, numericality: {only_integer: true}
  validates :amount_of_seats, :rows, numericality: {only_intgere: true, greater_than: 0}

  protected

  def correCt
    if :type == "Грузовой"
      :rows            = nil
      :buis_st         = nil
      :eco_st          = nil
      :prem_st         = nil
      :amount_of_seats = nil
    end
  end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :set_plane, only: [:show, :edit, :update, :destroy]

  # GET /planes
  # GET /planes.json
  def index
    @planes = Plane.all
  end

  # GET /planes/1
  # GET /planes/1.json
  def show
  end

  # GET /planes/new
  def new
    @plane = Plane.new
  end

  # GET /planes/1/edit
  def edit
  end

  # POST /planes
  # POST /planes.json
  def create
    @plane = Plane.new(plane_params)

    respond_to do |format|
      if @plane.save
        format.html { redirect_to @plane, notice: 'Plane was successfully created.' }
        format.json { render :show, status: :created, location: @plane }
      else
        format.html { render :new }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planes/1
  # PATCH/PUT /planes/1.json
  def update
    respond_to do |format|
      if @plane.update(plane_params)
        format.html { redirect_to @plane, notice: 'Plane was successfully updated.' }
        format.json { render :show, status: :ok, location: @plane }
      else
        format.html { render :edit }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planes/1
  # DELETE /planes/1.json
  def destroy
    @plane.destroy
    respond_to do |format|
      format.html { redirect_to planes_url, notice: 'Plane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane
      @plane = Plane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plane_params
      params.require(:plane).permit(:num, :model, :floors, :rows, :buis_st, :prem_st, :eco_st)
    end
end

app/helpers/planes_helper.rb
module PlanesHelper
  def select_ptype(name, selected = nil)
    select_tag(name, options_for_select(["Грузовой","Пассажирский"], [selected]))
  end
end

app/views/planes/_form.html.erb
<%= form_for(@plane) do |f| %>
  <% if @plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plane.errors.count, "error") %> prohibited this plane from being saved:</h2>

      <ul>
      <% @plane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :num %><br>
    <%= f.number_field :num %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :floors %><br>
    <%= f.number_field :floors %>
  </div>
  <div class="field">
    <%= f.label :rows %><br>
    <%= f.number_field :rows %>
  </div>
  <div class="field">
    <%= f.label :buis_st %><br>
    <%= f.text_field :buis_st %>
  </div>
  <div class="field">
    <%= f.label :prem_st %><br>
    <%= f.text_field :prem_st %>
  </div>
  <div class="field">
    <%= f.label :eco_st %><br>
    <%= f.text_field :eco_st %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planes/edit.html.erb
<h1>Editing Plane</h1>

<%= render 'form' %>

<%= link_to 'Show', @plane %> |
<%= link_to 'Back', planes_path %>

app/views/planes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Planes</h1>

<table>
  <thead>
    <tr>
      <th>Num</th>
      <th>Model</th>
      <th>Floors</th>
      <th>Rows</th>
      <th>Buis st</th>
      <th>Prem st</th>
      <th>Eco st</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planes.each do |plane| %>
      <tr>
        <td><%= plane.num %></td>
        <td><%= plane.model %></td>
        <td><%= plane.floors %></td>
        <td><%= plane.rows %></td>
        <td><%= plane.buis_st %></td>
        <td><%= plane.prem_st %></td>
        <td><%= plane.eco_st %></td>
        <td><%= link_to 'Show', plane %></td>
        <td><%= link_to 'Edit', edit_plane_path(plane) %></td>
        <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plane', new_plane_path %>

app/views/planes/new.html.erb
<h1>New Plane</h1>

<%= render 'form' %>

<%= link_to 'Back', planes_path %>

app/views/planes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num:</strong>
  <%= @plane.num %>
</p>

<p>
  <strong>Model:</strong>
  <%= @plane.model %>
</p>

<p>
  <strong>Floors:</strong>
  <%= @plane.floors %>
</p>

<p>
  <strong>Rows:</strong>
  <%= @plane.rows %>
</p>

<p>
  <strong>Buis st:</strong>
  <%= @plane.buis_st %>
</p>

<p>
  <strong>Prem st:</strong>
  <%= @plane.prem_st %>
</p>

<p>
  <strong>Eco st:</strong>
  <%= @plane.eco_st %>
</p>

<%= link_to 'Edit', edit_plane_path(@plane) %> |
<%= link_to 'Back', planes_path %>