config/routes.rb
Rails.application.routes.draw do

  resources :planes

  resources :passenger_tickets

  resources :passengers
  
  root to: 'flights#index', via: [:get, :post]

  match ':controller(/:action(/:id))(.:format)', via: [:get, :post]

end

app/models/passenger_ticket.rb
class UniqPassenger < ActiveModel::Validator
  def validate(record)
    if record.new_record? && Passenger.includes(passenger_tickets: {ticket: [:flight]}).where(passenger_tickets: { passenger: record.passenger}).size > 0
      record.errors[:passenger] << "Такой пассажир уже зарегистрирован на рейс!"
    end
  end
end

class PassengerTicket < ActiveRecord::Base
  before_validation :genNumber
  belongs_to        :passenger
  belongs_to        :ticket

  validates :e_num, :ttype,  presence: true
  validates :ttype,          inclusion: {in: ["Детский","Взрослый"],  message: "Такой тип билета не существует" }
  validates :e_num,          format: {with: /\A[0-9]{13}\z/ }
  validates_with UniqPassenger

  protected

  def genNumber
    if new_record?
      c = Company.includes(flights: {tickets: [:passenger_ticket]}).where(passenger_tickets: {id: self.id}).limit(1).pluck('companies.id')
      e = (PassengerTicket.includes(ticket: {flight: [:company]}).where(companies: {id: c}).count + 1).to_s
      self.e_num = "0" * (13 - e.size) + e
    end
  end
end

app/controllers/passenger_tickets_controller.rb
class PassengerTicketsController < ApplicationController
  before_action :set_passenger_ticket, only: [:show, :edit, :update, :destroy]
  before_action :get_pass_fl, only: [:new, :create, :edit, :update]
  before_action :check_params, only: [:new]

  # GET /passenger_tickets
  # GET /passenger_tickets.json
  def index
    @passenger_tickets = PassengerTicket.all
  end

  # GET /passenger_tickets/1
  # GET /passenger_tickets/1.json
  def show
  end

  # GET /passenger_tickets/new
  def new
    @passenger_ticket = PassengerTicket.new()
  end

  # GET /passenger_tickets/1/edit
  def edit
    @flight = @passenger_ticket.ticket.flight.id
  end

  # POST /passenger_tickets
  # POST /passenger_tickets.json
  def create
    @passenger_ticket = PassengerTicket.new(passenger_ticket_params)

    tik = Ticket.where(seat_num: @seat_num).first
    pas = Passenger.where(id: params[:passenger_id]).first
    @passenger_ticket.ticket    = tik
    @passenger_ticket.passenger = pas

    respond_to do |format|
      if @passenger_ticket.save
        format.html { redirect_to @passenger_ticket, notice: 'Passenger ticket was successfully created.' }
      else
        flash[:notice] = "Пассажир уже зарегистрирован на рейс."
        format.html { redirect_to controller: :flights, action: :index, is_departure: true}
      end
    end
  end

  # PATCH/PUT /passenger_tickets/1
  # PATCH/PUT /passenger_tickets/1.json
  def update
    @passenger_ticket.attributes = passenger_ticket_params

    tik = Ticket.where(seat_num: @seat_num).first
    @passenger_ticket.ticket    = tik

    respond_to do |format|
      if @passenger_ticket.update(passenger_ticket_params)
        format.html { redirect_to @passenger_ticket, notice: 'Passenger ticket was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /passenger_tickets/1
  # DELETE /passenger_tickets/1.json
  def destroy
    @passenger_ticket.destroy
    respond_to do |format|
      format.html { redirect_to passenger_tickets_url, notice: 'Passenger ticket was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger_ticket
      @passenger_ticket = PassengerTicket.find(params[:id])
    end

    def get_pass_fl
        @seat_num  = params[:seat_num]
        @passenger = params[:cid]
        @flight    = params[:fid]
    end

    def check_params
      if !params.has_key?(:cid) && params.has_key?(:fid)
        flash[:params] = "Необходимо ввести данные"
        redirect_to controller: :passengers, action: :new, fid: params[:fid]
      elsif !params.has_key?(:fid)
        flash[:params] = "Необходимо выбрать рейс"
        redirect_to controller: :flights, action: :index, is_departure: true
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_ticket_params
      params.require(:passenger_ticket).permit(:fid, :cid, :seat_num, :passenger_id, :ticket_id, :ttype)
    end
end

app/helpers/passenger_tickets_helper.rb
module PassengerTicketsHelper
  def select_free_seats(name, selected = nil, flight_id)
    select_tag(name, options_for_select(
    Ticket.joins('LEFT OUTER JOIN passenger_tickets ON tickets.id = passenger_tickets.ticket_id LEFT OUTER JOIN flights ON flights.id = tickets.flight_id').where('passenger_tickets.ticket_id IS ? AND flights.id = ?', nil, flight_id).load.map{ |x| [x.seat_num] } ,
    [selected]))
  end
  def select_type(name, selected = nil)
    select_tag(name, options_for_select(["Детский","Взрослый"], [selected]))
  end
end

app/views/passenger_tickets/_form.html.erb
<%= form_for(@passenger_ticket) do |f| %>
<%= hidden_field_tag("passenger_id", @passenger) %>
<%= hidden_field_tag("flight_id", @flight) %>
<%= hidden_field_tag("seat_num", @seat_num) %>
  <% if @passenger_ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passenger_ticket.errors.count, "error") %> prohibited this passenger_ticket from being saved:</h2>

      <ul>
      <% @passenger_ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= label_tag('passenger_ticket[ticket_id]',
      Ticket.human_attribute_name(:seat_num)) %><br>
    <%= select_free_seats('seat_num',
      @seat_num, @flight) %>
  </div>
  <div>
    <%= label_tag('passenger_ticket[ttype]',
      Ticket.human_attribute_name(:ttype)) %><br>
    <%= select_type('passenger_ticket[ttype]',
      @passenger_ticket.ttype) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/passenger_tickets/edit.html.erb
<h1>Редактирование билета</h1>

<%= render 'form' %>

<%= link_to 'Подробнее', @passenger_ticket %> |
<%= link_to 'Назад', passenger_tickets_path %>

app/views/passenger_tickets/index.html.erb
<h1>Все билеты</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Электронный номер билета</th>
      <th>Пассажир</th>
      <th>Номмер места</th>
      <th>Тип билета</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @passenger_tickets.each do |passenger_ticket| %>
      <tr>
        <td><%= passenger_ticket.e_num %></td>
        <td><%= link_to 'Подробнее', controller: :passengers, action: :show, id: passenger_ticket.passenger_id %></td>
        <td><%= passenger_ticket.ticket.seat_num %></td>
        <td><%= passenger_ticket.ticket.seat_class %></td>
        <td><%= passenger_ticket.ttype %></td>
        <td><%= link_to 'Показать', passenger_ticket %></td>
        <td><%= link_to 'Редактировать', edit_passenger_ticket_path(passenger_ticket) %></td>
        <td><%= link_to 'Удалить', passenger_ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Зарегистрировать нового пассажира', new_passenger_ticket_path %>

app/views/passenger_tickets/new.html.erb
<h1>Новый билет</h1>

<%= render 'form' %>
<%= link_to 'Назад к рейсам', controller: :flights, action: :index %>

app/views/passenger_tickets/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<p>
  <strong><%= Ticket.human_attribute_name(:e_num) %></strong>
  <%= @passenger_ticket.e_num %>
</p>

<p>
  <strong><%= Ticket.human_attribute_name(:seat_class) %>:</strong>
  <%= @passenger_ticket.ticket.seat_class %>
</p>

<p>
  <strong><%= Ticket.human_attribute_name(:seat_num) %>:</strong>
  <%= @passenger_ticket.ticket.seat_num %>
</p>

<p>
  <strong><%= Ticket.human_attribute_name(:price) %>:</strong>
  <%= @passenger_ticket.ticket.price %>
</p>

<p>
  <strong><%= Ticket.human_attribute_name(:seat_class) %>:</strong>
  <%= @passenger_ticket.ticket.seat_class %>
</p>

<p>
  <strong><%= PassengerTicket.human_attribute_name(:ttype) %>:</strong>
  <%= @passenger_ticket.ttype %>
</p>

<p>
  <strong><%= Passenger.human_attribute_name(:snl) %>:</strong>
  <%= @passenger_ticket.passenger.sname + " " + @passenger_ticket.passenger.name + " " + @passenger_ticket.passenger.lname %>
  <%= link_to 'Подробнее', controller: :passengers, action: :show, id: @passenger_ticket.passenger.id  %>
</p>

<%= link_to 'Редактировать', controller: :passenger_tickets, action: :edit, fid: @passenger_ticket.ticket.flight.id, cid: @passenger_ticket.passenger_id %> |
<%= link_to 'Назад', passenger_tickets_path %>