config/routes.rb
Rails.application.routes.draw do

  resources :planes

  resources :passenger_tickets

  resources :passengers
  
  root to: 'flights#index', via: [:get, :post]

  match ':controller(/:action(/:id))(.:format)', via: [:get, :post]

end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  has_many :passenger_tickets, dependent: :destroy

  validates :name, :sname, :passport_num, :foreign_passport,
            :citizenship, :sex, :bdate, presence: true
  validates :name, :sname,              format: {with: /\A[A-Z][a-z]+\z/,     message: "Только латинские буквы" }
  validates :lname,                     format: {with: /\A[A-Z][a-z]+\z/,     message: "Только латинские буквы" }, if: "!lname.blank?"
  validates :citizenship,               format: {with: /\A[A-Z][A-Za-z ]+\z/, message: "Только латинские буквы" }
  validates :passport_num,              format: {with: /\A[0-9]{10}\z/,       message: "Только цифры" }
  validates :foreign_passport,          format: {with: /\A[0-9]{9}\z/,        message: "Только цифпы" }
  validates :sex,                       inclusion: {in: ["м","ж"],            message: "Может быть только м или ж"}
  validates :foreign_passport,          uniqueness: true
  validates :passport_num,              uniqueness: true

end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show, :edit, :update, :destroy]
  before_action :transit_flight, only: [:new, :create]

  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers
  def create
    @passenger = Passenger.new(passenger_params)

    puts @flight

    respond_to do |format|
      if (p = Passenger.where(passport_num: @passenger.passport_num, foreign_passport: @passenger.foreign_passport).pluck(:id)).size > 0
        format.html { redirect_to controller: :passenger_tickets, action: :new, cid: p.first, fid: @fid }
      elsif @passenger.save
        format.html { redirect_to controller: :passenger_tickets, action: :new, cid: @passenger.id, fid: @fid }
      else
        format.html { render :new}
      end
    end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Пассажир был успешно создан' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Пассажир был успешно удален' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    def transit_flight
      if params.has_key?(:fid)
        @fid = params[:fid]
      else
        flash[:params] = "Необходимо выбрать рейс!"
        redirect_to controller: :flights, action: :index, is_departure: true
      end
      @fid = params[:fid]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_params
      params.require(:passenger).permit(:pnger, :fid ,:name, :lname, :sname, :passport_num, :foreign_passport, :citizenship, :sex, :bdate)
    end
end

app/helpers/passengers_helper.rb
module PassengersHelper
  def select_sex(name, selected = nil)
    select_tag(name, options_for_select(["м","ж"], [selected]))
  end

  def select_passenger(name, selected = nil)
    p = Passenger.pluck(:id).to_a
    select_tag(name, options_for_select(p, [selected]))
  end
end

app/views/passengers/_form.html.erb
<%= form_for(@passenger) do |f| %>
<%= hidden_field_tag("fid", @fid) %>
  <% if @passenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
      <% @passenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label Passenger.human_attribute_name(:name) %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label Passenger.human_attribute_name(:sname) %><br>
    <%= f.text_field :sname %>
  </div>
  <div class="field">
    <%= f.label Passenger.human_attribute_name(:lname) %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label Passenger.human_attribute_name(:passport_num) %><br>
    <%= f.text_field :passport_num %>
  </div>
  <div class="field">
    <%= f.label Passenger.human_attribute_name(:foreign_passport) %><br>
    <%= f.text_field :foreign_passport %>
  </div>
  <div class="field">
    <%= f.label Passenger.human_attribute_name(:citizenship) %><br>
    <%= f.text_field :citizenship %>
  </div>
  <div>
    <%= label_tag('passenger[sex]',
    Passenger.human_attribute_name(:sex)) %><br>
    <%= select_sex('passenger[sex]',
    @passenger.sex) %>
  </div>
  <div class="field">
    <%= f.label Passenger.human_attribute_name(:bdate) %><br>
    <%= f.date_select(:bdate, start_year: (Date.today.year - 125), end_year: Date.today.year) %>
  </div>
  <div class="actions">
    <%= f.submit(fid: @fid) %>
  </div>
<% end %>

app/views/passengers/edit.html.erb
<h1>Редактирование пассажира</h1>

<%= render 'form' %>

<%= link_to 'Показать', @passenger %> |
<%= link_to 'Назад', passengers_path %>

app/views/passengers/index.html.erb
<h1>Все пассажиры</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Фамилия</th>
      <th>Имя</th>
      <th>Отчество</th>
      <th>Номер паспорта</th>
      <th>Загранпаспорт</th>
      <th>Гражданство</th>
      <th>Пол</th>
      <th>Дата рождения</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.sname %></td>
        <td><%= passenger.name %></td>
        <td><%= passenger.lname %></td>
        <td><%= passenger.passport_num %></td>
        <td><%= passenger.foreign_passport %></td>
        <td><%= passenger.citizenship %></td>
        <td><%= passenger.sex %></td>
        <td><%= passenger.bdate %></td>
        <td><%= link_to 'Показать', passenger %></td>
        <td><%= link_to 'Редактировать', edit_passenger_path(passenger) %></td>
        <td><%= link_to 'Удалить', passenger, method: :delete, data: { confirm: 'Вы уверены что хотите удалить?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Зарегистрировать пассажира', new_passenger_path %>

app/views/passengers/new.html.erb
<h1>Новый пассажир</h1>

<%= render 'form' %>

<%= link_to 'Выбранный рейс', controller: :flights, action: :show, id: @fid %> |
<%= link_to 'Назад', passengers_path %>

app/views/passengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Passenger.human_attribute_name(:lname) %></strong>
  <%= @passenger.lname %>
</p>

<p>
  <strong><%= Passenger.human_attribute_name(:name) %></strong>
  <%= @passenger.name %>
</p>

<p>
  <strong><%= Passenger.human_attribute_name(:sname) %></strong>
  <%= @passenger.sname %>
</p>

<p>
  <strong><%= Passenger.human_attribute_name(:passport_num) %></strong>
  <%= @passenger.passport_num %>
</p>

<p>
  <strong><%= Passenger.human_attribute_name(:foreign_passport) %></strong>
  <%= @passenger.foreign_passport %>
</p>

<p>
  <strong><%= Passenger.human_attribute_name(:citizenship) %></strong>
  <%= @passenger.citizenship %>
</p>

<p>
  <strong><%= Passenger.human_attribute_name(:sex) %></strong>
  <%= @passenger.sex %>
</p>

<p>
  <strong><%= Passenger.human_attribute_name(:bdate) %></strong>
  <%= @passenger.bdate %>
</p>

<%= link_to 'Редактироват', edit_passenger_path(@passenger) %> |
<%= link_to 'Назад', passengers_path %>